### ISSUE TITLE
Videbreakdown project ToDo - 

### ISSUE THREAD

**Issue by jainpiyush26** [jainpiyush26/videobreakdown#2]
- [x] Get the FFMPEG configuration added
- [x] Extract just a few frames (test with ffmpeg -i in.mp4 -vf select='eq(n\,100)+eq(n\,184)+eq(n\,213)' -vsync 0 frames%d.jpg
) as an example
- [x] Get the frames logic setup
- [x] Export the correct size and aspect ratio images (1/10 or 1/5)
- [x] Combine all the data and start looking into PDF creator
- [x] Start setting the main executable
- [x] Generate the requirements.txt
